{{- if and .Values.node.enabled (not .Values.node.cleanupOnly) }}
{{- if or .Values.node.daemonset.priorityClassCreate .Values.node.gke.autopilot }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "falcon-cluster-guard.priorityClassName" . }}
  labels:
    {{- include "falcon-cluster-guard.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-guard
value: {{ .Values.node.daemonset.priorityClassValue }}
globalDefault: false
description: "Priority class for the CrowdStrike Falcon Cluster Guard node sensor DaemonSet."
{{- end }}
{{- end }}
