{{- $registryConfigJson := include "falcon-clusterguard.registryConfigJson" . }}
{{- if $registryConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-clusterguard.fullname" . }}-pull-secret
  namespace: {{ include "falcon-clusterguard.namespace" . }}
  labels:
    {{- include "falcon-clusterguard.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ $registryConfigJson }}
type: kubernetes.io/dockerconfigjson
{{- end }}
