apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falcon-clusterguard.nodeServiceAccountName" . }}
  namespace: {{ include "falcon-clusterguard.namespace" . }}
  labels:
    {{- include "falcon-clusterguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterguard
  {{- if .Values.node.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.node.serviceAccount.annotations | nindent 4 }}
  {{- end }}
---
{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "falcon-clusterguard.clusterServiceAccountName" . }}
  namespace: {{ include "falcon-clusterguard.namespace" . }}
  labels:
    {{- include "falcon-clusterguard.labels" . | nindent 4 }}
    app.kubernetes.io/component: clusterguard
  {{- if .Values.cluster.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.cluster.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
