# Default values for falcon-platform umbrella chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration shared across all Falcon components
global:
  # CrowdStrike Customer ID (CID) - required for all components if not using falconSecret
  falcon:
    cid:

  # Global Falcon Secret configuration
  # Name of existing Kubernetes secret containing sensitive Falcon configuration values
  # Secret must be in the same namespace as the component deployment
  # Required data:
  #   - FALCONCTL_OPT_CID
  # Required data if falcon-image-analyzer enabled:
  #   - AGENT_CID
  #   - AGENT_CLIENT_ID
  #   - AGENT_CLIENT_SECRET
  # Optional data:
  #   - FALCONCTL_OPT_PROVISIONING_TOKEN
  falconSecretName:

  # Container registry configuration
  # Used by components that support top level registry configuration (falcon-kac, falcon-image-analyzer)
  docker:
    pullSecret:

    # Value must be base64. Global pullSecret is not supported.
    # The base64 encoded string of the docker config json for the pull secret can be gotten through:
    # $ cat ~/.docker/config.json | base64 -
    registryConfigJSON:

# Enable/disable individual components
# Set enabled: true to deploy, enabled: false to skip

# Falcon Sensor - Runtime node protection
falcon-sensor:
  enabled: true
  # Override specific values for falcon-sensor
    
  node:
    enabled: true
    backend: bpf

    image:
      repository: registry.crowdstrike.com/falcon-sensor/us-1/release/falcon-sensor
      tag: latest

  container:
    enabled: false

# Falcon Kubernetes Admission Controller - Policy enforcement
falcon-kac:
  enabled: true
  # Override specific values for falcon-kac
  
  image:
    repository: registry.crowdstrike.com/falcon-kac/us-1/release/falcon-kac
    tag: latest

# Falcon Image Analyzer - Container image security scanning
falcon-image-analyzer:
  enabled: false  # Disabled by default due to additional configuration requirements
  # Override specific values for falcon-image-analyzer

  deployment:
    enabled: true
  daemonset:
    enabled: false
    
  crowdstrikeConfig:
    clusterName: ""     # Required - Kubernetes cluster name
  #  clientID: ""       # Required if not using global.falconSecretName - OAuth API Client ID
  #  clientSecret: ""   # Required if not using global.falconSecretName - OAuth API Client Secret
  #  agentRegion: ""    # Optional - CrowdStrike Cloud region, default: 'autodiscovery'

