# Default values for falcon-platform umbrella chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global configuration shared across all Falcon components
global:
  # CrowdStrike Customer ID (CID) - required for all components if not using falconSecret
  # falcon:
  #   cid: ""
    
  # Global Falcon Secret configuration
  # Used by components that support external secret injection (falcon-sensor, falcon-kac)
  falconSecret:
    # Enable Kubernetes secrets to inject sensitive Falcon values
    # When enabled, overrides falcon.cid and other sensitive values
    enabled: false
    
    # Name of existing Kubernetes secret containing Falcon configuration
    # Secret must be in the same namespace as the component deployment
    # Required keys: FALCONCTL_OPT_CID (and optionally FALCONCTL_OPT_PROVISIONING_TOKEN)
    # secretName: ""
    
  # Container registry configuration
  # Used by components that support top level registry configuration (falcon-kac, falcon-image-analyzer)
  registry:
    pullPolicy: Always

    # Value must be base64. Global pullSecret is not supported.
    # The base64 encoded string of the docker config json for the pull secret can be gotten through:
    # $ cat ~/.docker/config.json | base64 -
    registryConfigJSON:

# Enable/disable individual components
# Set enabled: true to deploy, enabled: false to skip

# Falcon Sensor - Runtime node protection
falcon-sensor:
  enabled: true
  # Override specific values for falcon-sensor

  falcon:
    # Will inherit global.falcon.cid if not specified
    # cid: ""
    
  # Will inherit global.falconSecret if not specified
  # falconSecret:
  #   enabled: false
  #   secretName: ""
    
  node:
    enabled: true
    backend: bpf

    image:
      repository: registry.crowdstrike.com/falcon-sensor/us-1/release/falcon-sensor
      tag: latest

  container:
    enabled: false

# Falcon Kubernetes Admission Controller - Policy enforcement
falcon-kac:
  enabled: true
  # Override specific values for falcon-kac

  falcon:
  # Will inherit global.falcon.cid if not specified
  #  cid: ""

# Will inherit global.falconSecret if not specified
#  falconSecret:
#    enabled: false
#    secretName: ""
  
  image:
    repository: registry.crowdstrike.com/falcon-kac/us-1/release/falcon-kac
    tag: latest

# Falcon Image Analyzer - Container image security scanning
falcon-image-analyzer:
  enabled: false  # Disabled by default due to additional configuration requirements
  # Override specific values for falcon-image-analyzer

  deployment:
    enabled: true
  daemonset:
    enabled: false
    
  crowdstrikeConfig:
    clusterName: ""     # Required - Kubernetes cluster name
    cid: ""             # Required - Falcon customer ID
    existingSecret: ""  # Optional - Name of existing secret containing AGENT_CLIENT_ID and AGENT_CLIENT_SECRET
  #  clientID: ""       # Required if not using existingSecret - OAuth API Client ID
  #  clientSecret: ""   # Required if not using existingSecret - OAuth API Client Secret
  #  agentRegion: ""    # Optional - CrowdStrike Cloud region, default: 'autodiscovery'

