# Default values for falcon-platform umbrella chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Namespace management configuration
# Enable automatic namespace creation - ignores already existing namespaces
createComponentNamespaces: true

# Global configuration shared across all Falcon components
global:
  # Falcon Customer ID (CID) - required for all components if not using falconSecret
  falcon:
    cid:

  # Global Falcon Secret configuration
  # Use an existing Kubernetes secret containing sensitive Falcon configuration values
  # Secret must be in the same namespace as the installed namespace
  # Required data:
  #   - FALCONCTL_OPT_CID
  # Required data if falcon-image-analyzer enabled:
  #   - AGENT_CID
  #   - AGENT_CLIENT_ID
  #   - AGENT_CLIENT_SECRET
  # Optional data:
  #   - FALCONCTL_OPT_PROVISIONING_TOKEN
  falconSecret:
    enabled: false
    secretName: ""

  # Container registry configuration
  # Used by components that support top level registry configuration (falcon-kac, falcon-image-analyzer)
  docker:
    # Name of existing Kubernetes docker registry secret
    pullSecret: ""

    # Value must be base64. Global pullSecret is not supported.
    # The base64 encoded string of the docker config json for the pull secret can be gotten through:
    # $ cat ~/.docker/config.json | base64 -
    registryConfigJSON: ""

# Enable/disable individual components
# Set enabled: true to deploy, enabled: false to skip

# Falcon Sensor - Runtime node protection
# Override specific values for falcon-sensor
falcon-sensor:
  enabled: false
  namespaceOverride: falcon-sensor

# Falcon Kubernetes Admission Controller - Policy enforcement
# Override specific values for falcon-kac
falcon-kac:
  enabled: false
  namespaceOverride: falcon-kac

# Falcon Image Analyzer - Container image security scanning
# Override specific values for falcon-image-analyzer
falcon-image-analyzer:
  enabled: false  # Disabled by default due to additional configuration requirements
  namespaceOverride: falcon-image-analyzer
