{{- if and .Values.node.enabled (not .Values.node.cleanupOnly) }}
{{- if (include "registryConfigJson" .) }}
{{- $registry := (include "registryConfigJson" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-sensor.fullname" . }}-pull-secret
  namespace: {{ include "falcon-sensor.namespace" . }}
data:
  .dockerconfigjson: {{ $registry }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
