{{- $falconSecretKeys := list "cid" "provisioning_token" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "falcon-kac.fullname" . }}-config
  namespace: {{ include "falcon-kac.namespace" . }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
data:
  __CS_ADMISSION_CONTROL_ENABLED: {{ .Values.admissionControl.enabled | quote }}
  {{- include "falcon-kac.generateWatcherEnvVars" . | nindent 2 }}
  {{- if not .Values.falconSecret.enabled }}
  FALCONCTL_OPT_CID: {{ .Values.falcon.cid }}
  {{- if .Values.falcon.provisioning_token }}
  FALCONCTL_OPT_PROVISIONING_TOKEN: {{ .Values.falcon.provisioning_token }}
  {{- end }}
  {{- end }}

  {{- range $key, $value := .Values.falcon }}
  {{- if and (or $value (eq ($value | toString) "false")) (not (has $key $falconSecretKeys)) }}
  FALCONCTL_OPT_{{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

{{- if .Values.clusterName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-kac-meta
  namespace: {{ include "falcon-kac.namespace" . }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
data:
  ClusterName: {{ .Values.clusterName }}
{{- end -}}
