apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "falcon-kac.fullname" . }}-rq
  namespace: {{ include "falcon-kac.namespace" . }}
  labels:
    {{- include "falcon-kac.labels" . | nindent 4 }}
spec:
  hard:
    pods: {{ .Values.resourceQuota.pods }}
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-cluster-critical
