{{ if or (.Values.crowdstrikeConfig.dockerAPIToken) (include "falcon-image-analyzer.registryConfigJson" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falcon-image-analyzer.fullname" . }}-pull-secret
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
{{- if .Values.crowdstrikeConfig.dockerAPIToken }}
  .dockerconfigjson: {{ template "falcon-image-analyzer.imagePullSecret" . }}
{{- end }}
{{- if (include "falcon-image-analyzer.registryConfigJson" .) }}
  .dockerconfigjson: {{ include "falcon-image-analyzer.registryConfigJson" . }}
{{- end }}
{{- end }}
