apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default ( include "falcon-image-analyzer.fullname" . ) }}
  namespace: {{ include "falcon-image-analyzer.namespace" . }}
  labels:
  {{- include "falcon-image-analyzer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
